package model;
// default package
// Generated Nov 24, 2014 3:39:25 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Dictionary generated by hbm2java
 */
public class Dictionary implements java.io.Serializable {

	private Integer id;
	private Language languageByLanguage1;
	private Language languageByLanguage2;
	private String name;
	private int owner;
	private Float maxScore;
	private Date bestTime;
	private String wordListPath;
	private Set userDictionaries = new HashSet(0);

	public Dictionary() {
	}

	public Dictionary(Language languageByLanguage1,
			Language languageByLanguage2, int owner) {
		this.languageByLanguage1 = languageByLanguage1;
		this.languageByLanguage2 = languageByLanguage2;
		this.owner = owner;
	}

	public Dictionary(Language languageByLanguage1,
			Language languageByLanguage2, String name, int owner,
			Float maxScore, Date bestTime, String wordListPath,
			Set userDictionaries) {
		this.languageByLanguage1 = languageByLanguage1;
		this.languageByLanguage2 = languageByLanguage2;
		this.name = name;
		this.owner = owner;
		this.maxScore = maxScore;
		this.bestTime = bestTime;
		this.wordListPath = wordListPath;
		this.userDictionaries = userDictionaries;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Language getLanguageByLanguage1() {
		return this.languageByLanguage1;
	}

	public void setLanguageByLanguage1(Language languageByLanguage1) {
		this.languageByLanguage1 = languageByLanguage1;
	}

	public Language getLanguageByLanguage2() {
		return this.languageByLanguage2;
	}

	public void setLanguageByLanguage2(Language languageByLanguage2) {
		this.languageByLanguage2 = languageByLanguage2;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getOwner() {
		return this.owner;
	}

	public void setOwner(int owner) {
		this.owner = owner;
	}

	public Float getMaxScore() {
		return this.maxScore;
	}

	public void setMaxScore(Float maxScore) {
		this.maxScore = maxScore;
	}

	public Date getBestTime() {
		return this.bestTime;
	}

	public void setBestTime(Date bestTime) {
		this.bestTime = bestTime;
	}

	public String getWordListPath() {
		return this.wordListPath;
	}

	public void setWordListPath(String wordListPath) {
		this.wordListPath = wordListPath;
	}

	public Set getUserDictionaries() {
		return this.userDictionaries;
	}

	public void setUserDictionaries(Set userDictionaries) {
		this.userDictionaries = userDictionaries;
	}

}
