package model;
// default package
// Generated Nov 24, 2014 3:39:25 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * GroupNumber generated by hbm2java
 */
public class GroupNumber implements java.io.Serializable {

	private Integer id;
	private Set userGroups = new HashSet(0);

	public GroupNumber() {
	}

	public GroupNumber(Set userGroups) {
		this.userGroups = userGroups;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Set getUserGroups() {
		return this.userGroups;
	}

	public void setUserGroups(Set userGroups) {
		this.userGroups = userGroups;
	}

}
