package model;
// default package
// Generated Nov 24, 2014 3:39:25 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Language generated by hbm2java
 */
public class Language implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set dictionariesForLanguage1 = new HashSet(0);
	private Set dictionariesForLanguage2 = new HashSet(0);

	public Language() {
	}

	public Language(String name, Set dictionariesForLanguage1,
			Set dictionariesForLanguage2) {
		this.name = name;
		this.dictionariesForLanguage1 = dictionariesForLanguage1;
		this.dictionariesForLanguage2 = dictionariesForLanguage2;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getDictionariesForLanguage1() {
		return this.dictionariesForLanguage1;
	}

	public void setDictionariesForLanguage1(Set dictionariesForLanguage1) {
		this.dictionariesForLanguage1 = dictionariesForLanguage1;
	}

	public Set getDictionariesForLanguage2() {
		return this.dictionariesForLanguage2;
	}

	public void setDictionariesForLanguage2(Set dictionariesForLanguage2) {
		this.dictionariesForLanguage2 = dictionariesForLanguage2;
	}

}
