package model;
// default package
// Generated Nov 24, 2014 3:39:25 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Statistics generated by hbm2java
 */
public class Statistics implements java.io.Serializable {
	
	private Integer id;
	private Float maxScore;
	private Date bestTime;
	private Integer dictionariesCount;
	private Integer friendsCount;

	public Statistics() {
	}

	public Statistics(Float maxScore, Date bestTime, Integer dictionariesCount,
			Integer friendsCount) {
		this.maxScore = maxScore;
		this.bestTime = bestTime;
		this.dictionariesCount = dictionariesCount;
		this.friendsCount = friendsCount;
	}
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Float getMaxScore() {
		return this.maxScore;
	}

	public void setMaxScore(Float maxScore) {
		this.maxScore = maxScore;
	}

	public Date getBestTime() {
		return this.bestTime;
	}

	public void setBestTime(Date bestTime) {
		this.bestTime = bestTime;
	}

	public Integer getDictionariesCount() {
		return this.dictionariesCount;
	}

	public void setDictionariesCount(Integer dictionariesCount) {
		this.dictionariesCount = dictionariesCount;
	}

	public Integer getFriendsCount() {
		return this.friendsCount;
	}

	public void setFriendsCount(Integer friendsCount) {
		this.friendsCount = friendsCount;
	}

}
