package model;

import javax.persistence.Embeddable;
// default package
// Generated Nov 24, 2014 3:39:25 PM by Hibernate Tools 4.3.1

/**
 * UserDictionaryId generated by hbm2java
 */
@Embeddable
public class UserDictionaryId implements java.io.Serializable {

	private int id;
	private int userid;
	private int dictionaryid;

	public UserDictionaryId() {
	}

	public UserDictionaryId(int id, int userid, int dictionaryid) {
		this.id = id;
		this.userid = userid;
		this.dictionaryid = dictionaryid;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public int getDictionaryid() {
		return this.dictionaryid;
	}

	public void setDictionaryid(int dictionaryid) {
		this.dictionaryid = dictionaryid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserDictionaryId))
			return false;
		UserDictionaryId castOther = (UserDictionaryId) other;

		return (this.getId() == castOther.getId())
				&& (this.getUserid() == castOther.getUserid())
				&& (this.getDictionaryid() == castOther.getDictionaryid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getUserid();
		result = 37 * result + this.getDictionaryid();
		return result;
	}

}
