package model;
// default package
// Generated Nov 24, 2014 3:39:25 PM by Hibernate Tools 4.3.1

/**
 * UserGroup generated by hbm2java
 */
public class UserGroup implements java.io.Serializable {

	private Integer id;
	private GroupNumber groupNumber;
	private int userid;

	public UserGroup() {
	}

	public UserGroup(GroupNumber groupNumber, int userid) {
		this.groupNumber = groupNumber;
		this.userid = userid;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public GroupNumber getGroupNumber() {
		return this.groupNumber;
	}

	public void setGroupNumber(GroupNumber groupNumber) {
		this.groupNumber = groupNumber;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

}
